const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,ground=455,$=id=>document.getElementById(id);
const catImg=new Image();catImg.src="images/cat.png";
const ui={score:$("score"),best:$("best"),level:$("level"),lives:$("lives"),progress:$("progress"),combo:$("combo"),stageLabel:$("stageLabel"),jumpCount:$("jumpCount"),fish:$("fish"),snack:$("snack"),star:$("star"),speed:$("speed"),jumpPower:$("jumpPower"),dashPower:$("dashPower"),nextExp:$("nextExp"),exp:$("exp"),missionText:$("missionText"),missionStatus:$("missionStatus"),abilityText:$("abilityText")};
let wind=0,windTimer=0,skillGauge=100,skillCooldown=0,particles=[],effects=[], skin=localStorage.getItem("uchinokoSkin")||"normal",soundOn=localStorage.getItem("uchinokoSound")!=="off",bgmOn=localStorage.getItem("uchinokoBgm")!=="off",audioCtx=null,bgmTimer=null,keys={},running=false,paused=false,last=0,score=0,best=+localStorage.getItem("uchinokoBest")||0,level=1,exp=0,lives=3,world=0,combo=0,comboTimer=0,stage=1,notice="",noticeTime=0,shake=0;
let collection={fish:0,snack:0,star:0},ability={name:"なし",time:0,shield:0},mission,items=[],obstacles=[],platforms=[],jumpPads=[],enemies=[],boss=null,goalX=900;
const SAVE_KEY="uchinokoProgressV25";
let stats=JSON.parse(localStorage.getItem(SAVE_KEY)||'null')||{plays:0,totalItems:0,stageBest:{1:0,2:0,3:0},stageTime:{1:null,2:null,3:null},achievements:{},noDamage:true,stageStart:0,damageTaken:0};
const achievementDefs=[{id:"first",name:"はじめの一歩",desc:"ゲームを1回プレイする",ok:()=>stats.plays>=1},{id:"collector",name:"ねこコレクター",desc:"アイテムを30個集める",ok:()=>stats.totalItems>=30},{id:"level3",name:"成長する猫",desc:"レベル3に到達する",ok:()=>level>=3},{id:"clear1",name:"おうち制覇",desc:"ステージ1をクリアする",ok:()=>!!stats.achievements.clear1},{id:"clear2",name:"夜の冒険者",desc:"ステージ2をクリアする",ok:()=>!!stats.achievements.clear2},{id:"nodamage",name:"無傷の達人",desc:"ダメージなしでステージをクリアする",ok:()=>!!stats.achievements.nodamage}];
function saveStats(){localStorage.setItem(SAVE_KEY,JSON.stringify(stats));updateRecordsUI()}
function unlock(id){if(!stats.achievements[id]){stats.achievements[id]=true;notice="実績解除！";noticeTime=100;beep(880,.12);saveStats()}}
function checkAchievements(){for(const a of achievementDefs)if(a.ok())unlock(a.id)}
function fmtTime(sec){return sec==null?"--":sec.toFixed(1)+"秒"}
function updateRecordsUI(){const q=id=>document.getElementById(id);if(!q("playCount"))return;q("playCount").textContent=stats.plays;q("totalItems").textContent=stats.totalItems;q("stage1Best").textContent=stats.stageBest[1]||0;q("stage2Best").textContent=stats.stageBest[2]||0;q("stage1Time").textContent=fmtTime(stats.stageTime[1]);q("stage2Time").textContent=fmtTime(stats.stageTime[2]);const unlocked=achievementDefs.filter(a=>stats.achievements[a.id]).length;q("achievementCount").textContent=unlocked; q("achievementList").innerHTML=achievementDefs.map(a=>`<div class="achievement ${stats.achievements[a.id]?"unlocked":""}">${stats.achievements[a.id]?"🏆":"🔒"} <b>${a.name}</b><small>${a.desc}</small></div>`).join("")}

const p={x:90,y:390,w:54,h:54,vy:0,onGround:false,face:1,jumps:0,maxJumps:2,inv:0};
function missionNew(){mission={type:["fish","combo","star"][Math.floor(Math.random()*3)],target:3,reward:100,done:false};if(mission.type==="combo"){mission.target=5;mission.reward=150}if(mission.type==="star"){mission.target=1;mission.reward=200}}
function reset(s=stage){stage=s;stats.damageTaken=0;stats.noDamage=true;stats.stageStart=performance.now();score=0;level=1;exp=0;lives=3;combo=0;comboTimer=0;ability={name:"なし",time:0,shield:0};skillGauge=100;skillCooldown=0;collection={fish:0,snack:0,star:0};missionNew();p.x=90;p.y=390;p.vy=0;p.onGround=false;p.jumps=0;p.inv=0;boss=null;platforms=[];jumpPads=[];
 if(stage===1){items=[...[180,310,470,650].map((x,i)=>({x,y:390-(i%2)*22,r:14,type:"fish",value:10,got:false})),...[250,550,760].map(x=>({x,y:365,r:16,type:"snack",value:30,got:false})),...[400,720].map(x=>({x,y:335,r:18,type:"star",value:100,got:false}))];obstacles=[{x:350,y:435,w:45,h:20},{x:590,y:435,w:48,h:20},{x:800,y:435,w:42,h:20}];jumpPads=[{x:445,y:438,w:58,h:17,power:15}];platforms=[{x:515,y:350,w:120,h:16,kind:"high"}];enemies=[];goalX=900}
 else if(stage===2){items=[...[150,280,430,580,730].map((x,i)=>({x,y:390-(i%2)*22,r:14,type:"fish",value:15,got:false})),...[220,500,780].map(x=>({x,y:365,r:16,type:"snack",value:40,got:false})),...[350,650].map(x=>({x,y:335,r:18,type:"star",value:120,got:false}))];obstacles=[{x:300,y:435,w:42,h:20},{x:520,y:435,w:45,h:20},{x:760,y:435,w:42,h:20}];platforms=[{x:360,y:365,w:115,h:16,baseY:365,range:55,speed:.035,phase:0,kind:"moving"},{x:585,y:315,w:120,h:16,baseY:315,range:45,speed:.045,phase:2,kind:"moving"}];enemies=[{x:390,y:405,w:38,h:38,vx:1.1,alive:true},{x:680,y:405,w:38,h:38,vx:-1.2,alive:true}];goalX=840;boss={x:900,y:365,w:70,h:90,hp:3,maxHp:3,vx:-.8,active:true}}
 else{wind=0;windTimer=0;particles=[];items=[...[150,260,380,500,620,760].map((x,i)=>({x,y:390-(i%3)*28,r:14,type:"fish",value:20,got:false})),...[300,560,820].map(x=>({x,y:350,r:16,type:"snack",value:50,got:false})),...[430,700].map(x=>({x,y:300,r:18,type:"star",value:150,got:false}))];obstacles=[{x:250,y:435,w:42,h:20},{x:470,y:435,w:45,h:20},{x:690,y:435,w:42,h:20}];jumpPads=[{x:335,y:438,w:58,h:17,power:15},{x:610,y:438,w:58,h:17,power:15}];platforms=[{x:390,y:350,w:120,h:16,kind:"high"},{x:650,y:300,w:130,h:16,kind:"high"},{x:785,y:240,w:105,h:16,kind:"window"}];enemies=[{x:540,y:405,w:38,h:38,vx:1,alive:true}];goalX=900;boss=null}updateUI()}
function updateUI(){ui.score.textContent=score;ui.best.textContent=best;ui.level.textContent=level;ui.lives.textContent=lives;ui.combo.textContent=combo;ui.stageLabel.textContent=stage;ui.jumpCount.textContent=p.jumps+"/"+p.maxJumps;ui.progress.textContent=Math.min(100,Math.floor(p.x/(stage===3?goalX+120:stage===2?goalX+90:goalX)*100))+"%";ui.fish.textContent=collection.fish;ui.snack.textContent=collection.snack;ui.star.textContent=collection.star;ui.speed.textContent=(1+(level-1)*.18).toFixed(2);ui.jumpPower.textContent=(1+(level-1)*.22).toFixed(2);ui.dashPower.textContent=(1+(level-1)*.28).toFixed(2);ui.exp.textContent=exp;ui.nextExp.textContent=(50-exp%50)+"pt";const sg=document.getElementById("skillGauge");if(sg)sg.textContent=Math.floor(skillGauge)+"%";const sb=document.getElementById("skillBtn"),ss=document.getElementById("skillState");if(sb){sb.disabled=skillGauge<100||skillCooldown>0;sb.textContent=skillCooldown>0?"チャージ中…":"E：にゃんこスキル"}if(ss){ss.textContent=ability.time>0?"ACTIVE":skillCooldown>0?"CHARGE":"READY";ss.className="skill-state "+(ability.time>0?"active":skillCooldown>0?"cooldown":"ready")}ui.abilityText.textContent=ability.name+(ability.time>0?" ("+Math.ceil(ability.time/60)+"秒)":"");let t=mission.type==="fish"?"魚を3個集める":mission.type==="combo"?"コンボを5までつなぐ":"星を1個集める";let n=mission.type==="fish"?collection.fish:mission.type==="combo"?combo:collection.star;ui.missionText.textContent=t+"（報酬 "+mission.reward+"pt）";ui.missionStatus.textContent=mission.done?"達成！":n+"/"+mission.target}
function add(n){score+=n;if(score>best){best=score;localStorage.setItem("uchinokoBest",best)}}
function levelUp(){level++;notice="レベルアップ！ 能力が上がった";noticeTime=120}
function activate(n,t){ability.name=n;ability.time=t}
function useSkill(){if(!running||paused||skillGauge<100||skillCooldown>0)return;skillGauge=0;skillCooldown=600;document.querySelector(".skill-panel")?.classList.add("flash");setTimeout(()=>document.querySelector(".skill-panel")?.classList.remove("flash"),500);ability={name:"🌟 にゃんこスキル",time:300,shield:1};p.inv=300;burst(p.x+p.w/2,p.y+p.h/2,"spark",35);add(100);notice="にゃんこスキル発動！";noticeTime=90;beep(1040,.18)}
function collect(i){burst(i.x,i.y,"spark",12);beep(760,.05);i.got=true;combo++;comboTimer=180;let m=combo>=10?5:combo>=5?3:combo>=3?2:1;add(i.value*m);collection[i.type]++;stats.totalItems++;checkAchievements();exp+=i.value;if(i.type==="star"&&Math.random()<.5)activate("🐾 猫ダッシュ",300);if(i.type==="snack"&&Math.random()<.4)activate("🍖 おやつ2倍",360);while(exp>=50){exp-=50;levelUp()}let n=mission.type==="fish"?collection.fish:mission.type==="combo"?combo:collection.star;if(!mission.done&&n>=mission.target){mission.done=true;add(mission.reward);exp+=mission.reward;notice="ミッション達成！ +"+mission.reward;noticeTime=120;while(exp>=50){exp-=50;levelUp()}}notice=(m>1?"COMBO x"+m+"! ":"")+(i.type==="fish"?"🐟":i.type==="snack"?"🍪":"⭐")+" +"+i.value;noticeTime=65;updateUI()}
function damage(){if(p.inv>0)return;burst(p.x+p.w/2,p.y+p.h/2,"hit",16);if(ability.shield){ability.shield=0;ability.name="なし";p.inv=75;notice="バリアで防いだ！";noticeTime=70;return}lives--;stats.damageTaken++;stats.noDamage=false;combo=0;p.inv=75;p.x=Math.max(30,p.x-55);p.vy=-5;shake=10;notice="ダメージ！";noticeTime=45;if(lives<=0)over()}
function over(){checkAchievements();saveStats();running=false;show("ゲームオーバー","ステージ"+stage+" / スコア："+score+" / アイテム："+(collection.fish+collection.snack+collection.star)+"個")}
function clear(){running=false;const elapsed=(performance.now()-stats.stageStart)/1000;stats.stageBest[stage]=Math.max(stats.stageBest[stage]||0,score);if(stats.stageTime[stage]==null||elapsed<stats.stageTime[stage])stats.stageTime[stage]=elapsed;if(stage===1)stats.achievements.clear1=true;if(stage===2)stats.achievements.clear2=true;if(stats.noDamage)stats.achievements.nodamage=true;checkAchievements();saveStats();show("ステージ"+stage+" クリア！","スコア："+score+" / レベル："+level+" / クリアタイム："+elapsed.toFixed(1)+"秒 / ミッション："+(mission.done?"達成":"未達成"))}
function audio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(freq=440,dur=.06,vol=.04){if(!soundOn)return;try{const a=audio(),o=a.createOscillator(),g=a.createGain();o.type="sine";o.frequency.value=freq;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(vol,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.start();o.stop(a.currentTime+dur)}catch(e){}}
function beep(freq=440,dur=.06){tone(freq,dur,.045)}
function startBgm(){if(!bgmOn||bgmTimer)return;let notes=[261.6,329.6,392,329.6,293.7,349.2,440,349.2],i=0;bgmTimer=setInterval(()=>{if(running&&!paused)tone(notes[i++%notes.length],.18,.012)},420)}
function stopBgm(){clearInterval(bgmTimer);bgmTimer=null}
function show(t,x,b="もう一度遊ぶ"){
 const result=/クリア|CLEAR|GAME OVER|ゲームオーバー/.test(t);
 $("overlayTitle").textContent=t;$("overlayText").textContent=x;$("startBtn").textContent=b;$("overlay").classList.toggle("result-overlay",result);
 const panel=document.querySelector(".title-panel");
 let box=document.getElementById("resultStats");
 if(result){if(!box){box=document.createElement("div");box.id="resultStats";box.className="result-stats";panel.insertBefore(box,$("startBtn"));}
 const elapsed=stats.stageStart?((performance.now()-stats.stageStart)/1000):0;
 box.innerHTML=`<div><span>STAGE</span><b>${stage}</b></div><div><span>SCORE</span><b>${score}</b></div><div><span>LEVEL</span><b>${level}</b></div><div><span>ITEMS</span><b>${collection.fish+collection.snack+collection.star}</b></div>`;
 }else if(box)box.remove();$("overlay").style.display="flex";
}function hide(){$("overlay").style.display="none"}
function burst(x,y,type="dust",count=8){for(let i=0;i<count;i++)effects.push({x,y,vx:(Math.random()-.5)*3,vy:-Math.random()*2.5-0.5,life:35,max:35,type})}
function jump(){if(!running||paused)return;beep(620);burst(p.x+p.w/2,p.y+p.h,"dust",10);if(p.jumps<p.maxJumps){p.vy=-(10.5+(level-1)*.22);p.jumps++;p.onGround=false;notice=p.jumps===2?"二段ジャンプ！":"ジャンプ！";noticeTime=25}}
function update(dt){if(paused)return;if(skillCooldown>0)skillCooldown-=dt;skillGauge=Math.min(100,skillGauge+0.12*dt);if(p.inv>0)p.inv-=dt;if(comboTimer>0)comboTimer-=dt;else combo=0;if(ability.time>0)ability.time-=dt;else ability.name="なし";let dir=(keys.ArrowRight||keys.right?1:0)-(keys.ArrowLeft||keys.left?1:0),dash=keys.Shift||keys.dash,boost=ability.name.includes("猫ダッシュ")?1.7:1;p.vx=dir*(3.1+(level-1)*.18)*(dash?1.8+(level-1)*.28:1)*boost;if(dir)p.face=dir;p.x=Math.max(20,Math.min(stage===3?goalX+120:stage===2?goalX+90:goalX,p.x+p.vx*dt));p.vy+=.52*dt;p.y+=p.vy*dt;if(p.y+p.h>=ground){if(!p.onGround&&p.vy>3)burst(p.x+p.w/2,ground,"dust",12);p.y=ground-p.h;p.vy=0;p.onGround=true;p.jumps=0}
 for(const pad of jumpPads){if(p.x+p.w>pad.x&&p.x<pad.x+pad.w&&p.y+p.h>=pad.y&&p.y+p.h<=pad.y+24&&p.vy>=0){p.y=pad.y-p.h;p.vy=-pad.power;p.jumps=1;notice="ジャンプ台で大ジャンプ！";noticeTime=45;beep(760)}}
 for(const pl of platforms){if(pl.kind==="moving"){pl.y=pl.baseY+Math.sin(world*pl.speed+pl.phase)*pl.range}if(p.x+p.w-5>pl.x&&p.x+5<pl.x+pl.w&&p.y+p.h>=pl.y&&p.y+p.h<=pl.y+20&&p.vy>=0){p.y=pl.y-p.h;p.vy=0;p.onGround=true;p.jumps=0}}
 for(const i of items)if(!i.got&&Math.hypot(p.x+p.w/2-i.x,p.y+p.h/2-i.y)<35)collect(i);for(const o of obstacles)if(p.x+p.w-8>o.x&&p.x+8<o.x+o.w&&p.y+p.h>o.y+4&&p.y<o.y+o.h){damage();break}
 for(const e of enemies)if(e.alive){e.x+=e.vx*dt;if(e.x<100||e.x>780)e.vx*=-1;if(p.x+p.w-8>e.x&&p.x+8<e.x+e.w&&p.y+p.h>e.y+4&&p.y<e.y+e.h){if(p.vy>1&&p.y+p.h<e.y+18){e.alive=false;p.vy=-7;add(80);notice="敵を踏んだ！ +80";noticeTime=50}else damage()}}
 if(stage===2&&boss&&boss.active){boss.x+=boss.vx*dt;if(boss.x<700||boss.x>900)boss.vx*=-1;if(p.x+p.w>boss.x&&p.x<boss.x+boss.w&&p.y+p.h>boss.y&&p.y<boss.y+boss.h){if(p.vy>1&&p.y+p.h<boss.y+20){boss.hp--;p.vy=-8;add(200);notice="ボスに攻撃！";noticeTime=60;if(boss.hp<=0){boss.active=false;goalX=940;notice="ボス撃破！ゴールへ！";noticeTime=120}}else damage()}}if(stage===3){windTimer-=dt;if(windTimer<=0){wind=wind===0?1:0;windTimer=180;notice=wind?"窓からそよ風！":"風がやんだ！";noticeTime=45}if(wind&&p.y<390)p.x=Math.min(goalX+120,p.x+0.35*dt);if(Math.random()<0.18){particles.push({x:goalX+20+Math.random()*90,y:120+Math.random()*220,vx:-.4,life:100})}}for(const q of particles){q.x+=q.vx*dt;q.life-=dt}particles=particles.filter(q=>q.life>0);for(const e of effects){e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=.08*dt;e.life-=dt}effects=effects.filter(e=>e.life>0);world+=dt;shake=Math.max(0,shake-dt);noticeTime=Math.max(0,noticeTime-dt);updateUI();if(stage===1&&p.x>=goalX-20)clear();if(stage===2&&boss&&!boss.active&&p.x>=goalX-20)clear();if(stage===3&&p.x>=goalX-20)clear()}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,stage===1?"#a9ddff":stage===2?"#20264f":"#f6c6d8");g.addColorStop(1,stage===1?"#fff1cf":stage===2?"#6d5a8b":"#fff0d5");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle=stage===1?"#f7d7a7":stage===2?"#27304f":"#d9a77b";ctx.fillRect(0,ground,W,H-ground);if(stage===3){
 // Stage 3: unmistakable window-side scenery
 ctx.fillStyle="rgba(255,255,210,.62)";
 ctx.beginPath();ctx.moveTo(560,0);ctx.lineTo(960,0);ctx.lineTo(960,330);ctx.lineTo(560,330);ctx.closePath();ctx.fill();
 // window outer frame
 const wx=620,wy=78,ww=245,wh=245;
 ctx.fillStyle="#8b5a3c";ctx.fillRect(wx-18,wy-18,ww+36,wh+36);
 ctx.fillStyle="#9fdcff";ctx.fillRect(wx,wy,ww,wh);
 // sky gradient-like bands
 ctx.fillStyle="#c9efff";ctx.fillRect(wx,wy,ww,wh*.48);
 ctx.fillStyle="#a8d9f5";ctx.fillRect(wx,wy+wh*.48,ww,wh*.52);
 // distant rooftops / greenery
 ctx.fillStyle="#8fc58a";ctx.beginPath();ctx.moveTo(wx,wy+wh);ctx.lineTo(wx+55,wy+wh-48);ctx.lineTo(wx+110,wy+wh);ctx.lineTo(wx+165,wy+wh-62);ctx.lineTo(wx+ww,wy+wh-18);ctx.lineTo(wx+ww,wy+wh);ctx.closePath();ctx.fill();
 // sun
 ctx.fillStyle="#ffd75c";ctx.beginPath();ctx.arc(wx+190,wy+52,28,0,Math.PI*2);ctx.fill();
 // clouds
 ctx.fillStyle="rgba(255,255,255,.9)";
 for(const c of [{x:wx+38,y:wy+55,s:1},{x:wx+105,y:wy+105,s:.8}]){ctx.beginPath();ctx.arc(c.x,c.y,18*c.s,0,Math.PI*2);ctx.arc(c.x+22*c.s,c.y-10*c.s,24*c.s,0,Math.PI*2);ctx.arc(c.x+48*c.s,c.y,18*c.s,0,Math.PI*2);ctx.fillRect(c.x-2*c.s,c.y,52*c.s,18*c.s);ctx.fill();}
 // window crossbars
 ctx.fillStyle="#8b5a3c";ctx.fillRect(wx+ww/2-5,wy,10,wh);ctx.fillRect(wx,wy+wh/2-5,ww,10);
 // curtains, clearly visible
 ctx.fillStyle="#e88ca7";ctx.beginPath();ctx.moveTo(wx-42,wy-28);ctx.quadraticCurveTo(wx-8,wy+70,wx+20,wy+wh+30);ctx.lineTo(wx-35,wy+wh+30);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.moveTo(wx+ww+42,wy-28);ctx.quadraticCurveTo(wx+ww+8,wy+70,wx+ww-20,wy+wh+30);ctx.lineTo(wx+ww+35,wy+wh+30);ctx.closePath();ctx.fill();
 ctx.fillStyle="#d96f92";ctx.fillRect(wx-48,wy-34,ww+96,12);
 // sunlight rays
 ctx.fillStyle="rgba(255,245,170,.28)";ctx.beginPath();ctx.moveTo(wx+35,wy+wh);ctx.lineTo(wx+95,wy+wh);ctx.lineTo(wx+25,ground);ctx.lineTo(wx-35,ground);ctx.closePath();ctx.fill();
 // floating light motes
 for(const q of particles){ctx.fillStyle="rgba(255,255,220,.95)";ctx.beginPath();ctx.arc(q.x,q.y,3+Math.sin(world/8+q.x)*1.5,0,Math.PI*2);ctx.fill();}
 // wind lines when breeze is active
 if(wind){ctx.strokeStyle="rgba(255,255,255,.9)";ctx.lineWidth=3;for(let k=0;k<4;k++){const yy=145+k*38+Math.sin(world/10+k)*5;ctx.beginPath();ctx.moveTo(90+k*35,yy);ctx.quadraticCurveTo(145+k*35,yy-18,205+k*35,yy);ctx.stroke();}}
}ctx.fillStyle="#9d6b45";ctx.fillRect(goalX,300,48,155);ctx.fillStyle="#f4c56e";ctx.fillRect(goalX+8,315,32,140);for(const pad of jumpPads){ctx.fillStyle="#e8a33a";ctx.fillRect(pad.x,pad.y,pad.w,pad.h);ctx.fillStyle="#fff4b0";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText("JUMP",pad.x+pad.w/2,pad.y+13)}
 for(const pl of platforms){ctx.fillStyle=pl.kind==="moving"?"#4db6ac":pl.kind==="window"?"#e7a85b":"#b67a42";ctx.fillRect(pl.x,pl.y,pl.w,pl.h);ctx.fillStyle="rgba(255,255,255,.7)";ctx.fillRect(pl.x+8,pl.y+4,pl.w-16,3)}
 for(const o of obstacles){ctx.fillStyle="#777";ctx.fillRect(o.x,o.y,o.w,o.h)}for(const e of enemies)if(e.alive){ctx.fillStyle="#9b4d7b";ctx.beginPath();ctx.arc(e.x+19,e.y+19,19,0,7);ctx.fill()}for(const i of items)if(!i.got){ctx.font=(i.r*2)+"px serif";ctx.textAlign="center";ctx.fillText(i.type==="fish"?"🐟":i.type==="snack"?"🍪":"⭐",i.x,i.y+Math.sin(world/12+i.x)*4)}if(stage===2&&boss&&boss.active){ctx.fillStyle="#6e3e91";ctx.fillRect(boss.x,boss.y,boss.w,boss.h);ctx.fillStyle="#e85b6a";ctx.fillRect(boss.x,boss.y-15,boss.w*(boss.hp/boss.maxHp),7);ctx.fillStyle="#fff";ctx.font="14px sans-serif";ctx.fillText("BOSS",boss.x+12,boss.y-22)}if(p.inv<=0||Math.floor(p.inv/6)%2===0){ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.scale(p.face,1);if(catImg.complete&&catImg.naturalWidth){if(skin!=="normal"){ctx.filter=skin==="gold"?"sepia(1) saturate(2) hue-rotate(5deg)":skin==="night"?"hue-rotate(190deg) brightness(.75)":"none"}ctx.drawImage(catImg,-p.w/2,-p.h/2,p.w,p.h);ctx.filter="none";if(skin==="ribbon"){ctx.fillStyle="#e85b8b";ctx.beginPath();ctx.arc(-12,-23,7,0,7);ctx.arc(2,-23,7,0,7);ctx.fill();ctx.fillStyle="#ffd45c";ctx.beginPath();ctx.arc(-5,-23,4,0,7);ctx.fill()}}else{ctx.font="48px serif";ctx.fillText("🐱",0,12)}ctx.restore()}for(const e of effects){ctx.globalAlpha=Math.max(0,e.life/e.max);ctx.fillStyle=e.type==="hit"?"#ff6b6b":e.type==="spark"?"#ffe27a":"#d9b08c";ctx.beginPath();ctx.arc(e.x,e.y, e.type==="spark"?3:4,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(noticeTime>0){ctx.fillStyle="rgba(73,59,50,.85)";ctx.font="bold 24px sans-serif";ctx.textAlign="center";ctx.fillText(notice,W/2,70)}ctx.restore()}
function loop(t){if(!running)return;let dt=Math.min(2,(t-last)/16.67);last=t;update(dt);draw();requestAnimationFrame(loop)}
window.addEventListener("keydown",e=>{if(e.repeat&&e.key===" ")return;keys[e.key]=true;if(e.key==="p"||e.key==="P")paused=!paused;if(e.key==="c"||e.key==="C"){notice="図鑑：🐟"+collection.fish+" 🍪"+collection.snack+" ⭐"+collection.star;noticeTime=100}if(e.key===" ")jump();if(e.key==="e"||e.key==="E")useSkill();if(["ArrowLeft","ArrowRight"," ","Shift"].includes(e.key))e.preventDefault()});window.addEventListener("keyup",e=>keys[e.key]=false);
$("customBtn").onclick=(e)=>{e.preventDefault();const panel=$("customPanel");panel.style.display="flex";panel.setAttribute("aria-hidden","false");notice="猫カスタムを開きました";noticeTime=60};$("closeCustom").onclick=()=>{const panel=$("customPanel");panel.style.display="none";panel.setAttribute("aria-hidden","true")};document.querySelectorAll("[data-skin]").forEach(b=>b.onclick=()=>{skin=b.dataset.skin;localStorage.setItem("uchinokoSkin",skin);notice="猫の見た目を変更しました";noticeTime=90;$('customPanel').style.display="none";$('customPanel').setAttribute('aria-hidden','true')});
$("recordsBtn").onclick=()=>{updateRecordsUI();$("recordsPanel").style.display="flex";$("recordsPanel").setAttribute("aria-hidden","false")};$("closeRecords").onclick=()=>{$("recordsPanel").style.display="none";$("recordsPanel").setAttribute("aria-hidden","true")};
$("soundBtn").onclick=()=>{soundOn=!soundOn;localStorage.setItem("uchinokoSound",soundOn?"on":"off");$("soundBtn").textContent=soundOn?"🔊 効果音ON":"🔇 効果音OFF"};$("bgmBtn").onclick=()=>{bgmOn=!bgmOn;localStorage.setItem("uchinokoBgm",bgmOn?"on":"off");$("bgmBtn").textContent=bgmOn?"🎵 BGM ON":"🔇 BGM OFF";if(bgmOn)startBgm();else stopBgm()};$("resetSaveBtn").onclick=()=>{if(confirm("ベストスコアと記録をリセットしますか？")){localStorage.removeItem("uchinokoBest");localStorage.removeItem(SAVE_KEY);stats={plays:0,totalItems:0,stageBest:{1:0,2:0,3:0},stageTime:{1:null,2:null,3:null},achievements:{},noDamage:true,stageStart:0,damageTaken:0};best=0;updateUI();updateRecordsUI();notice="記録をリセットしました";noticeTime=100}};$("helpBtn").onclick=()=>show("操作説明","←→移動 / Space二段ジャンプ / Shiftダッシュ / ジャンプ台・動く足場を活用 / P一時停止 / C図鑑","閉じる");document.querySelectorAll("[data-key]").forEach(b=>{let k=b.dataset.key;b.addEventListener("pointerdown",()=>{if(k==="jump")jump();else keys[k]=true});["pointerup","pointerleave","pointercancel"].forEach(ev=>b.addEventListener(ev,()=>keys[k]=false))});
$("startBtn").onclick=()=>{stats.plays++;saveStats();reset(stage);running=true;paused=false;hide();audio();startBgm();last=performance.now();requestAnimationFrame(loop)};$("pauseBtn").onclick=()=>paused=!paused;$("skillBtn").onclick=useSkill;$("collectionBtn").onclick=()=>{notice="図鑑：🐟"+collection.fish+" 🍪"+collection.snack+" ⭐"+collection.star;noticeTime=100};$("stage1Btn").onclick=()=>{reset(1);window.dispatchEvent(new CustomEvent("uchinoko-stage-selected",{detail:1}));show("ステージ1：うちのおうち","昼のおうちを冒険しよう！","スタート")};$("stage2Btn").onclick=()=>{reset(2);window.dispatchEvent(new CustomEvent("uchinoko-stage-selected",{detail:2}));show("ステージ2：夜の庭","敵とボスを攻略しよう！","スタート")};$("stage3Btn").onclick=()=>{stage=3;reset(3);window.dispatchEvent(new CustomEvent("uchinoko-stage-selected",{detail:3}));show("ステージ3：窓辺の大冒険","窓辺を目指して足場とジャンプ台を使おう！","スタート")};$("soundBtn").textContent=soundOn?"🔊 効果音ON":"🔇 効果音OFF";$("bgmBtn").textContent=bgmOn?"🎵 BGM ON":"🔇 BGM OFF";reset(1);updateRecordsUI();draw();